apiVersion: v2
name: usrv-bio-track-training
version: 0.1.0
description: Bio Track microservice — usrv-bio-track-training
dependencies:
  - name: bio-track-base
    version: "0.1.0"
    repository: "file://../_base"
